### ISSUE TITLE
Napraviti prirodno skakanje

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-069-super-dario#1]
Kretanje prilikom skakanja nije prirodno - krece se konstantnom brzinom dok ne dodje do odredjene visine, pa se kreće na dole isto konstantnom brzinom.

Umesto toga, zbog gravitacije treba da usporava kad ide na gore, i ubrzava na dole.

**Comment by pavle995** [comment]
Promenjen je skok tako da ga opisuje funkcija parabole
