### ISSUE TITLE
Ne može da se skoči sa bloka

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-069-super-dario#2]
Kad se igrač nalazi na bloku, ne može da skoči.

- Napraviti da igrač može da skoči sa trenutne visine na kojoj je, gde god da je
- Napraviti blokove na više različitih visina da bi ovo iznad moglo da se testira

**Comment by pavle995** [comment]
Sad bi trebalo da moze da skoci sa bloka. Sada odakle god da skoci, skok je isti. Postoje 2 vrste bolka, i oni su na razlicitoj visini.
